### PR TITLE
Issue6

### PR DESCRIPTION
**Pull request by BenMartin94**
Replaced jamienicol with red-coracle in the relevent sections

### CODE REVIEW

**Comment by red-coracle** [comment]
Hey, thanks for the PR. I would change it slightly in two ways:
1. Change the package to `com.redcoracle.episodes` instead of `org.redcoracle.episodes` so it matches the applicationId in [build.gradle](https://github.com/red-coracle/episodes/blob/master/app/build.gradle#L17).
2. In AndroidManifest.xml, leave the name references as relative instead of explicit. For example, keep `android:name=".SettingsActivity"` instead of changing to `android:name="com.redcoracle.episodes.SettingsActivity"`.

**Comment by BenMartin94** [comment]
I have made your requested changes, let me know what you think

**Comment by red-coracle** [comment]
Looks good, but the `import com.redcoracle.episodes.R;` shouldn't be needed since it's in the same package.

**Comment by BenMartin94** [comment]
Good point, I just optimized the imports.  Should be good now.

**Comment by red-coracle** [comment]
Thanks!

**Comment by BenMartin94** [comment]
Haha looking back through my old stuff. I forgot I did this. It was for a course back in university. Had to contribute to an opensource project in case you were wondering why some random person came along and changed a bunch of imports.

**Pull request merged**
